### PR TITLE
Added custom util.inspect() function 

### PR DESCRIPTION
**Pull request by adrianhara**
If using `util.inspect` on a decimaljs instance, a lot of stuff will be printed out. However, usually the decimaljs instance is just a property in some object and you're `util.inspect`-ing that object so what you want is to just get the decimal value printed out. Starting from Node 10 the internal custom util inspect symbol is exposed so it's possible to add a custom inspect function to your objects that will be called at runtime by `util.inspect`. This is what this pull request aims to provide for decimaljs.

### CODE REVIEW

**Comment by MikeMcl** [comment]
I am committed to keeping this module ES3-compliant, so there would need to be a check for `Symbol`.

See, for example, the sister library, [bignumber.js](https://github.com/MikeMcl/bignumber.js/blob/master/bignumber.js#L2749) where a custom inspect function has been added previously.

The `Decimal.prototype` object is in scope as `P` so (untested):

```js
if (typeof Symbol == 'function' && typeof Symbol.iterator == 'symbol') {
  P[Symbol.for('nodejs.util.inspect.custom')] = P.valueOf;
}
```

**Comment by marcelh-gh** [comment]
does not seem to work for me.
Node 10.5.0
Decimal.js 10.1.1
still the entire object structure gets printed out.

**Comment by MikeMcl** [comment]
@marcelh-gh 

`Symbol.for('nodejs.util.inspect.custom')` is only available in node v10.12.0+.

**Comment by marcelh-gh** [comment]
@MikeMcl  Thanks for the quick reply! :-)

**Pull request merged**
