### PR TITLE
Fix toNearest rounding

### PR DESCRIPTION
**Pull request by luciavelasco**
This pull request will allow CEIL and ROUND_UP to work in the toNearest function, and adds tests to demonstrate it.

### CODE REVIEW

**Comment by MikeMcl** [comment]
Hello. Please explain further what the issue is, so it is easier for me to investigate.

**Comment by luciavelasco** [comment]
```
new Decimal(430).toNearest(new Decimal(100), Decimal.ROUND_CEIL)
```
Should result in 500 (because it should be ceiled to the nearest hundred), but results in 400, because this line:
```
if (rm < 4) rm = [4, 5, 7, 8][rm];
```
will replace ROUND_CEIL and ROUND_UP with ROUND_HALF_CEIL and ROUND_HALF_UP. So 430 is rounded down instead of up, because 30 is less than half of 100.

**Comment by MikeMcl** [comment]
Thanks for the explanation. I think we have different expectations of what a `toNearest` method should do.

The current behaviour is intended: the method always returns the *nearest* multiple of its argument, see [toNearest](http://mikemcl.github.io/decimal.js/#toNearest).

The rounding mode only comes in to play when the Decimal value is *equidistant* from two multiples.

Using your example, obviously 500 is not nearer 430 than 400 is, it is much further away, so surely the method is right to return 400. The rounding mode cannot be allowed to override the stipulation that the method always returns the nearest multiple.

What do you say to that?

By the way, something that this library needs at the moment, but what I haven't time to do, is to add the information that I posted at (this)[https://stackoverflow.com/questions/46744170/precision-issue-with-decimal-js-tan/48243281#48243281] stackoverflow question to the documentation *doc/API.html*, so users understand the precision limits of the trigonometric functions. If you were interested in doing that, that would be great. If not, thanks anyway!

**Comment by luciavelasco** [comment]
The rounding flag *should* come into play, because otherwise there is no point for the flag option to exist. `toNearest` is a form of rounding, but it rounds between steps, not decimal places or significant figures. Therefore any flag that is valid for rounding should be usable on `toNearest`, including ceiling or rounding up. You should have a different set of flags (not the `Decimal.ROUND_[TYPE]` ones) for this function if you do not want them to be able to ask for the nearest upper bound, or restrict them in the typings.

This is a valid rounding usecase that should not be ignored, because people will have to use a completely different library or build something bespoke to do something that yours *can* cater to when a flag that overrides the default behaviour is set. In my usecase I always need to find the nearest upper bound that an amount can fit into. For example, if I sell eggs in baskets of 100 and my user wants to buy 430 eggs, I can't give them 400 because it's not enough, but I can give them 500. If they want 400, the nearest upper bound is 400.

My alternative is to use toNearest without the flag option _that I should not be allowed to set if it will not give me the correct behaviour_, then to add my step (the first, or y, value in the `toNearest` method) if the nearest value is less than my own value. There is no need for me to do this if your rounding actually rounds the way I have asked it to in using the `Decimal.ROUND_CEIL` flag.

If you do not want this behaviour I will create a pull request that changes the typings of toNearest to only accept certain flags, and create another pull request with a duplicate function called `toNearestUpper`, that takes only the round up or round ceil flags (round up by default), because this is a valid mathematical usecase.

**Comment by MikeMcl** [comment]
> The rounding flag should come into play, because otherwise there is no point for the flag option to exist.

The flag is necessary for cases where the value is equidistant from two multiples.

 > toNearest is a form of rounding, but it rounds between steps, not decimal places or significant figures. Therefore any flag that is valid for rounding should be usable on toNearest, including ceiling or rounding up. 

That is hard to disagree with.

> You should have a different set of flags (not the Decimal.ROUND_[TYPE] ones) for this function if you do not want them to be able to ask for the nearest upper bound, or restrict them in the typings.

Yes, I think they should be restricted in the typings.

> In my usecase I always need to find the nearest upper bound that an amount can fit into. 

Sure, that is *your* usecase, but others may always want the *nearest* irrespective of direction and there is no easy way of producing that if the rounding mode is prioritised.

> There is no need for me to do this if your rounding actually rounds the way I have asked it to in using the Decimal.ROUND_CEIL flag.

From the perspective of how the method works at the moment, you have only used the flag to determine what happens if the value is equidistant from two multiples. 

I think your perspective is valid, and I agree that the method would be more consistent with the other rounding methods, and may perhaps be more useful and flexible, if it behaved as you suggest.

Then again, I have previously deliberately chose the current behaviour, and I would have done this only after considering the matter at length; there may have been good reasons for the choice which may not be immediately apparent to me or anyone else now.

Perhaps a configuration setting could be added which determines the behaviour, for example

```js
Decimal.set({ allowToNearestToNotReturnTheNearest: true });
```

I'll consider it further, don't change the PR yet.

**Comment by dave-harvey** [comment]
How about having a new function called `toUnit` that has the behaviour @luciavelasco requires? This would more closely describe the use case, and it would also avoid any confusion for those users of `toNearest` who use it as intended.

+1 for using eggs to explain [board lots](https://www.investopedia.com/terms/b/boardlot.asp) . 😸

**Comment by MikeMcl** [comment]
Okay, Lucia, I think you are right that it would be better if the method returned the nearest multiple in the direction of the rounding mode, not necessarily the outright nearest.

I was mistaken above when I wrote that there is no easy way of getting the outright nearest if the rounding mode is prioritised, as clearly using rounding modes 4, 5, 6, 7 and 8 do that.

In your PR, please remove the unnecessary line 
```js
if (rm === 1 || rm === 3) rm = [4, 5, 7, 8][rm];
```
Also, just above it in the method, please change
```js
if (rm !== void 0) checkInt32(rm, 0, 8);
```
to
```js
if (rm === void 0) rm = Ctor.rounding;
else checkInt32(rm, 0, 8);
```
Also, please change the test file to the following:

[toNearest.js.txt](https://github.com/MikeMcl/decimal.js/files/1778475/toNearest.js.txt)

If you do the above, I will accept the PR.

I will update the docs and publish a new release at the end of the week.

Thanks for your input.

@dave-harvey 

Thanks, Dave, but I'm going to go with this PR.

**Comment by dave-harvey** [comment]
@MikeMcl this works for us.  Many thanks for your help

**Comment by luciavelasco** [comment]
@MikeMcl the revisions are pushed, thanks for your advice and the updated test file!

**Pull request merged**
