### PR TITLE
Workaround for iOS 10.3 issue which caused wrong numbers to be returned.

### PR DESCRIPTION
**Pull request by raing3**
This seems to fix the issues I was having in #55.

Not sure if all of the changes are strictly required to fix the issue.

I've ran the tests in the "test" folder in iOS Safari (10.3), Chrome (v59) and Node - all seem to pass.
Prior to the changes the tests would bail out during the acos section with numerous failures on iOS 10.3.

If anything else is required to have these changes merged please let me know, or if it is not desired to introduce workarounds for iOS bugs into the codebase please feel welcome to decline the PR.

Personally, I think it is worth merging just to help prevent other people potentially stressing with the same problems I have.

### CODE REVIEW

**Comment by MikeMcl** [comment]
Okay, looks good, I will probably merge in a day or two.

The changes seem to reduce the performance of division by about 10% though, so it will be done reluctantly.

**Comment by MikeMcl** [comment]
Please let me know whether the following returns `true` or `false` on the afflicted Safari

```js
Object.keys({ '250': 0.5, '1000': 0.1 }).length === 2
```

**Comment by raing3** [comment]
That snippet returns false for me on iOS 10.3.2.

The object ends up containing 338 keys and looks like:

`{"0":null,"1":null,"2":null,"3":null,"4":null,"5":null,"6":null,"7":null,"8":null,"9":null,"10":null,"11":null,"12":null,"13":null,"14":null,"15":null,"16":null,"17":null,"18":null,"19":null,"20":null,"21":null,"22":null,"23":null,"24":null,"25":null,"26":null,"27":null,"28":null,"29":null,"30":null,"31":null,"32":null,"33":null,"34":null,"35":null,"36":null,"37":null,"38":null,"39":null,"40":null,"41":null,"42":null,"43":null,"44":null,"45":null,"46":null,"47":null,"48":null,"49":null,"50":null,"51":null,"52":null,"53":null,"54":null,"55":null,"56":null,"57":null,"58":null,"59":null,"60":null,"61":null,"62":null,"63":null,"64":null,"65":null,"66":null,"67":null,"68":null,"69":null,"70":null,"71":null,"72":null,"73":null,"74":null,"75":null,"76":null,"77":null,"78":null,"79":null,"80":null,"81":null,"82":null,"83":null,"84":null,"85":null,"86":null,"87":null,"88":null,"89":null,"90":null,"91":null,"92":null,"93":null,"94":null,"95":null,"96":null,"97":null,"98":null,"99":null,"100":null,"101":null,"102":null,"103":null,"104":null,"105":null,"106":null,"107":null,"108":null,"109":null,"110":null,"111":null,"112":null,"113":null,"114":null,"115":null,"116":null,"117":null,"118":null,"119":null,"120":null,"121":null,"122":null,"123":null,"124":null,"125":null,"126":null,"127":null,"128":null,"129":null,"130":null,"131":null,"132":null,"133":null,"134":null,"135":null,"136":null,"137":null,"138":null,"139":null,"140":null,"141":null,"142":null,"143":null,"144":null,"145":null,"146":null,"147":null,"148":null,"149":null,"150":null,"151":null,"152":null,"153":null,"154":null,"155":null,"156":null,"157":null,"158":null,"159":null,"160":null,"161":null,"162":null,"163":null,"164":null,"165":null,"166":null,"167":null,"168":null,"169":null,"170":null,"171":null,"172":null,"173":null,"174":null,"175":null,"176":null,"177":null,"178":null,"179":null,"180":null,"181":null,"182":null,"183":null,"184":null,"185":null,"186":null,"187":null,"188":null,"189":null,"190":null,"191":null,"192":null,"193":null,"194":null,"195":null,"196":null,"197":null,"198":null,"199":null,"200":null,"201":null,"202":null,"203":null,"204":null,"205":null,"206":null,"207":null,"208":null,"209":null,"210":null,"211":null,"212":null,"213":null,"214":null,"215":null,"216":null,"217":null,"218":null,"219":null,"220":null,"221":null,"222":null,"223":null,"224":null,"225":null,"226":null,"227":null,"228":null,"229":null,"230":null,"231":null,"232":null,"233":null,"234":null,"235":null,"236":null,"237":null,"238":null,"239":null,"240":null,"241":null,"242":null,"243":null,"244":null,"245":null,"246":null,"247":null,"248":null,"249":null,"250":0.5,"251":null,"252":null,"253":null,"254":null,"255":null,"256":null,"257":null,"258":null,"259":null,"260":null,"261":null,"262":null,"263":null,"264":null,"265":null,"266":null,"267":null,"268":null,"269":null,"270":null,"271":null,"272":null,"273":null,"274":null,"275":null,"276":null,"277":null,"278":null,"279":null,"280":null,"281":null,"282":null,"283":null,"284":null,"285":null,"286":null,"287":null,"288":null,"289":null,"290":null,"291":null,"292":null,"293":null,"294":null,"295":null,"296":null,"297":null,"298":null,"299":null,"300":null,"301":null,"302":null,"303":null,"304":null,"305":null,"306":null,"307":null,"308":null,"309":null,"310":null,"311":null,"312":null,"313":null,"314":null,"315":null,"316":null,"317":null,"318":null,"319":null,"320":null,"321":null,"322":null,"323":null,"324":null,"325":null,"326":null,"327":null,"328":null,"329":null,"330":null,"331":null,"332":null,"333":null,"334":null,"335":null,"336":null,"1000":0.1}`

**Comment by MikeMcl** [comment]
Thank you.

I would be grateful if you could also check the following

```js
console.log( Object.keys({ 2: 3}).length === 1 );
console.log( Object.keys({ 2: 3.4}).length === 1 ); 
console.log( Object.keys({ 2: 3, 5: 4 }).length === 2 );
console.log( Object.keys({ 2: 3.4, 5: 6.7 }).length === 2 );
```

Also, please could you check if the #55 issue is solved and all the tests pass if the following code is run before using *decimal.js* without this PR.

```js
if (Object.keys({'250': 0.5, '1000': 0.1}).length !== 2) {
  Array.prototype.unshift = function () {
    Array.prototype.splice.apply(this, Array.prototype.concat.apply([0, 0], arguments));
    return this.length;
  };
  Array.prototype.shift = function () {
    return Array.prototype.splice.call(this, 0, 1)[0];
  };
}
```

**Comment by raing3** [comment]
Sorry for the delay, forgot to do this Friday and only had access to an iPad again today.

`console.log( Object.keys({ 2: 3}).length === 1 ); // true
console.log( Object.keys({ 2: 3.4}).length === 1 );  // true
console.log( Object.keys({ 2: 3, 5: 4 }).length === 2 ); // true
console.log( Object.keys({ 2: 3.4, 5: 6.7 }).length === 2 ); // true`

> Also, please could you check if the #55 issue is solved and all the tests pass if the following code is run before using decimal.js without this PR.

Adding the snippet to the start of the script tag in test.html (from the master branch - 784a38a) makes all of the tests pass on iOS 10.3. :+1:

**Comment by MikeMcl** [comment]
Thanks for your help.

I think I'm going to go with the above snippet rather than the PR. It has the advantage of only making changes if the bug is present, and I can use it with all my libraries instead of making specific changes to each.

The question is whether to include it at the top of the library, or to publish it as a separate module so it can be included at the initiative of the user.

**Comment by raing3** [comment]
I've been using a forked version of Decimal.js for the past few years to work around the issue but will no longer be supporting iOS 10 so this is not an issue for me any more.

Closing the PR since it doesn't seem worth applying a workaround for this issue now.

**Pull request closed without merging**
